# Generated by Django 3.1.4 on 2021-08-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_preview',
            field=models.ImageField(default=123, upload_to='article_img/', verbose_name='Изображение в списке (334х234)'),
            preserve_default=False,
        ),
    ]
