# Generated by Django 3.1.4 on 2021-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название на английском')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Название на узбекском')),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=200, verbose_name='Автор на русском')),
                ('author_en', models.CharField(max_length=200, verbose_name='Автор на английском')),
                ('author_uz', models.CharField(max_length=200, verbose_name='Автор на узбекском')),
                ('short_description', models.TextField(verbose_name='Краткое описание на русском')),
                ('short_description_en', models.TextField(verbose_name='Краткое описание на английском')),
                ('short_description_uz', models.TextField(verbose_name='Краткое описание на узбекском')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
