# Generated by Django 3.1.4 on 2021-08-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210824_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='par_1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_1_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_1_uz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_2',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_2_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_2_uz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_3',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_3_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_3_uz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_4_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_4_uz',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_5_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='par_5_uz',
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default=123, verbose_name='Текст на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(default=123, verbose_name='Текст на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_uz',
            field=models.TextField(default=123, verbose_name='Текст на узбекском'),
            preserve_default=False,
        ),
    ]
