# Generated by Django 3.1.4 on 2022-04-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название продукта на русском')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Название продукта на узбекском')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название продукта на английском')),
                ('subtitle_en', models.CharField(max_length=500, verbose_name='Подзаголовок на английском')),
                ('subtitle_ru', models.CharField(max_length=500, verbose_name='Подзаголовок на русском')),
                ('subtitle_uz', models.CharField(max_length=500, verbose_name='Подзаголовок на узбекском')),
                ('price', models.FloatField(verbose_name='Цена продукта')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_en', models.TextField(verbose_name='Описание на английском')),
                ('description_uz', models.TextField(verbose_name='Описание на узбекском')),
                ('img_hover', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное фото')),
                ('img_preview', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото при наведении')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.category', verbose_name='Категория продукта')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
