# Generated by Django 3.1.4 on 2022-04-12 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20220411_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/', verbose_name='Фото продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фото продукта',
            },
        ),
    ]
