# Generated by Django 3.1.4 on 2022-04-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Показательная цена'),
        ),
    ]
