# Generated by Django 3.1.4 on 2021-06-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
